/**
 * Created by XpoHo
 */

const DEFAULT = 'UNAUTHORIZED';
const UNAUTHORIZED = 'UNAUTHORIZED';
const AUTHORIZED = 'AUTHORIZED';
const NEED_NEW_PASSWORD = 'NEED_NEW_PASSWORD';
const NEED_CONFIRM_PHONE = 'NEED_CONFIRM_PHONE';

export default {
  // статусы пользователя
  DEFAULT,
  UNAUTHORIZED,
  AUTHORIZED,
  NEED_NEW_PASSWORD,
  NEED_CONFIRM_PHONE,

}
